### ISSUE TITLE
你好，想咨询一下你使用R3live dataset的问题

### ISSUE THREAD

**Issue by hr2894235132** [ZikangYuan/sr_livo#2]
为什么我用ros看degenerate序列图像是640*512呢？

**Comment by ZikangYuan** [comment]
您好，不知道您说的是哪个序列。我刚粗略检查了一下代码，image_resize_ratio的值设置的是1，所以按道理来说是不会对图像进行resize操作的。

**Comment by hr2894235132** [comment]
> 您好，不知道您说的是哪个序列。我刚粗略检查了一下代码，image_resize_ratio的值设置的是1，所以按道理来说是不会对图像进行resize操作的。

感谢回复，您好！我在使用这三个退化序列的时候出现的问题，实际上我是想看看fast-livo在这三个序列上的效果，去相互做一下对比。
![image](https://github.com/ZikangYuan/sr_livo/assets/86639226/4977e866-37d4-495d-befb-c359290a24b9)

**Comment by ZikangYuan** [comment]
很抱歉，在这种雷达观测退化的序列上，SR-LIVO是无法正常工作的。至于您之前提到的degenerate序列图像是640*512，那说明那个序列的尺寸就是640*512(根据我检查代码后的结论应该是这样)。

**Comment by hr2894235132** [comment]
> 很抱歉，在这种雷达观测退化的序列上，SR-LIVO是无法正常工作的。至于您之前提到的degenerate序列图像是640*512，那说明那个序列的尺寸就是640x512(根据我检查代码后的结论应该是这样)。

不知道您有用过这三个序列跑过fast-livo嘛。我看到您在论文中也对比了fast-livo

**Comment by ZikangYuan** [comment]
木有额

**Comment by hr2894235132** [comment]
> 木有额

感谢您耐心回复！我再去尝试尝试。
祝好！
