### ISSUE TITLE
How to save colored point cloud (.PCD) data

### ISSUE THREAD

**Issue by Nationarity** [ZikangYuan/sr_livo#3]
Sorry for asking such a rudimentary question.
The "livo_r3live.launch" saves bias.txt, pose.txt and velocity.txt in the output folder,
I have confirmed that your code works fine, but is it not possible to save the .PCD files like R3Live?

**Comment by ZikangYuan** [comment]
Sorry for the late reply, now that I have added the code to store the final map, you can get **rgb_map.pcd** in the **output** folder after running SR-LIVO.
