### ISSUE TITLE
evaluation code for NTU-Viral

### ISSUE THREAD

**Issue by sijieaaa** [ZikangYuan/sr_livo#4]
Hi,

Thanks for your good work! 
May I know where the evaluation code for NTU-Viral is?

**Comment by ZikangYuan** [comment]
Hi. We utilize evo for evaluation, and you can find in on github.

**Comment by pengllbit** [comment]
你好，非常感谢你的工作以及开源！
我也想知道你是如何进行定位精度评测的，也为ntu数据集提供的pose GT和我们SLAM输出的pose不在同一坐标系，是如何转到同一坐标系进行evo评测的呢。ntu论文里的方法优化出一个T作为两个坐标系的对其，我似乎不是非常认同。请指教一下，非常感谢！！！
