### ISSUE TITLE
评测问题

### ISSUE THREAD

**Issue by pengllbit** [ZikangYuan/sr_livo#5]
你好，非常感谢你的工作以及开源！
我也想知道你是如何进行定位精度评测的，也为ntu数据集提供的pose GT和我们SLAM输出的pose不在同一坐标系，是如何转到同一坐标系进行evo评测的呢。ntu论文里的方法优化出一个T作为两个坐标系的对其，我似乎不是非常认同。请指教一下，非常感谢！！！

**Comment by ZikangYuan** [comment]
> 你好，非常感谢你的工作以及开源！ 我也想知道你是如何进行定位精度评测的，也为ntu数据集提供的pose GT和我们SLAM输出的pose不在同一坐标系，是如何转到同一坐标系进行evo评测的呢。ntu论文里的方法优化出一个T作为两个坐标系的对其，我似乎不是非常认同。请指教一下，非常感谢！！！

你好，我们是用evo进行轨迹对齐的，evo可以使用--align指令将GT与预测轨迹进行自动对齐，然后计算ATE

**Comment by pengllbit** [comment]
原来如此，我尝试下，非常感谢！！！
