### ISSUE TITLE
ouster error

### ISSUE THREAD

**Issue by yahyahajlaoui** [ZikangYuan/sr_livo#6]
Hello,
first thank you for your great work! 
I have an issue while using the launch file, It mesure the IMU and then the error '****** Remove_outlier_using_ransac_pnp error*****
' appears.
I searched for this error and I think it is a pose estimation error or a calibration error write ? do you know how can I solve the problem
I am using another data of an ouster os1-128.
here is the error.
Thank you so much for your work again.
![Screenshot from 2024-04-05 17-06-42](https://github.com/ZikangYuan/sr_livo/assets/87317026/0f08fd28-ba16-4886-b9a7-6acefeaf1773)
here is my config file : 
common:
    lidar_topic:  "/ouster/points"
    imu_topic:  "/imu/data"
    image_topic:  "/camera/image_raw"
    image_type:  RGB8    # 1 RGB8   2 COMPRESSED
    point_filter_num: 4
    time_sync_en: false         # ONLY turn on when external time synchronization is really not possible
    gravity_acc: [ 0.0, 0.0, 9.81]
    
lidar_parameter:
    lidar_type: 3                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
    N_SCANS: 128
    SCAN_RATE: 20                # only need to be set for velodyne, unit: Hz,
    time_unit: 3            # the unit of time/t field in the PointCloud2 rostopic: 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
    blind: 4
    fov_degree:    180
    det_range:     100.0

imu_parameter:
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    time_diff_enable: false
    
camera_parameter:
    image_width: 2048
    image_height: 1536
    camera_intrinsic: [ 1722.0259, 0.0, 962.0152,
                        0.0, 1715.7976, 753.9130,
                        0.0, 0.0, 1.0 ]
    camera_dist_coeffs: [-0.055235, -0.000564, -0.005090, -0.005836, 0.000000]  #k1, k2, p1, p2, k3

extrinsic_parameter:
    extrinsic_enable:  true      # true: enable the online estimation of IMU-LiDAR extrinsic,
    extrinsic_t_imu_lidar: [ 0.0, 0.0, 0.0 ]
    extrinsic_R_imu_lidar: [ 1, 0, 0, 
                             0, 1, 0, 
                             0, 0, 1 ]
    extrinsic_t_imu_camera: [-0.0673894,-0.04949313,-0.05140671]
    extrinsic_R_imu_camera: [-0.03108824 ,-0.99901124 ,-0.03178154,-0.01624026 ,-0.03128784  ,0.99937847,-0.9993847   ,0.03158506 ,-0.01525152]

**Comment by ZikangYuan** [comment]
This means that the vision module does not find a reassembled match, so the vision module does not use the current data to optimize the camera-parameters, but this does not affect the normal operation of the system.

**Comment by zszz3** [comment]
> This means that the vision module does not find a reassembled match, so the vision module does not use the current data to optimize the camera-parameters, but this does not affect the normal operation of the system.

您好，我在运行kitti数据集运行一半左右的时间后，系统卡住并只出现最后一句话，****** Remove_outlier_using_ransac_pnp error*****
这句话一直更新但速度极为缓慢
![{5E51B465-EFAE-4dcc-B225-22FC5445AEBE}](https://github.com/user-attachments/assets/0bc4e423-ace8-4b97-952f-4e32e50ec22f)
运行了接近一两个小时
