### ISSUE TITLE
IMU数据处理的疑问

### ISSUE THREAD

**Issue by mumu2000mumu** [ZikangYuan/sr_livo#7]
作者您好，这里w1和w2的计算是不是写反了，感觉w1应该用dt1进行计算

![2024-04-15 17-10-40屏幕截图](https://github.com/ZikangYuan/sr_livo/assets/156920466/4d3798e4-7b5a-474d-b76f-0c0afcdfaa28)

**Comment by ZikangYuan** [comment]
没有反呢，dt_1代表t_frame距离上一个IMU测量值的时间，dt_1越大，代表t_frame离上一个IMU测量值越远，所以上一个IMU测量值的占比应该越小。

**Comment by mumu2000mumu** [comment]
我懂了！感谢您的指导
